"use client";

import { ArrowLeft, ArrowRight, BedDouble, Building2, CarFront, Check, ImageIcon, MapPin, UtensilsCrossed } from "lucide-react";
import { useActionState, useState } from "react";
import { createHostListing } from "./actions";

type FormValues = { category: string; business_name: string; title: string; description: string; location: string; price: string; image_url: string; capacity: string; bedrooms: string; bathrooms: string; star_rating: string; luggage: string; amenities: string };
const initial: FormValues = { category: "airbnb", business_name: "", title: "", description: "", location: "", price: "", image_url: "", capacity: "1", bedrooms: "1", bathrooms: "1", star_rating: "3", luggage: "1", amenities: "" };
const inputClass = "mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100";
const categories = [{ id: "airbnb", label: "Vacation rental", icon: BedDouble }, { id: "hotel", label: "Hotel", icon: Building2 }, { id: "food", label: "Food & dining", icon: UtensilsCrossed }, { id: "transport", label: "Transport", icon: CarFront }];

export default function HostOnboardingForm() {
  const [step, setStep] = useState(1);
  const [values, setValues] = useState<FormValues>(initial);
  const [state, action, pending] = useActionState(createHostListing, undefined);
  const update = (name: keyof FormValues, next: string) => setValues((current) => ({ ...current, [name]: next }));
  const canContinue = step === 1 ? Boolean(values.category && values.business_name.trim()) : step === 2 ? values.title.trim().length >= 5 && values.description.trim().length >= 30 : step === 3 ? Boolean(values.location.trim() && Number(values.price) > 0 && values.image_url.trim()) : true;

  return <form action={action} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg">
    <div className="border-b border-slate-100 px-6 py-5"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-slate-400"><span>Step {step} of 4</span><span>{["Your business","Listing basics","Location & details","Review"][step - 1]}</span></div><div className="mt-3 grid grid-cols-4 gap-2">{[1,2,3,4].map((number) => <span key={number} className={`h-1.5 rounded-full ${number <= step ? "bg-violet-600" : "bg-slate-200"}`} />)}</div></div>
    <div className="min-h-[440px] p-6 sm:p-8">
      {step === 1 && <section><h2 className="text-2xl font-bold">What do you want to list?</h2><p className="mt-2 text-slate-500">Choose your primary service and tell travelers who is hosting.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{categories.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => update("category", id)} className={`flex items-center gap-3 rounded-2xl border-2 p-4 text-left font-semibold transition ${values.category === id ? "border-violet-600 bg-violet-50 text-violet-700" : "border-slate-200 hover:border-violet-200"}`}><Icon className="size-6" />{label}{values.category === id && <Check className="ml-auto size-5" />}</button>)}</div><label className="mt-6 block text-sm font-medium">Business or host name<input value={values.business_name} onChange={(event) => update("business_name", event.target.value)} className={inputClass} placeholder="Island Escape Tours" /></label></section>}
      {step === 2 && <section><h2 className="text-2xl font-bold">Introduce your listing</h2><p className="mt-2 text-slate-500">A clear title and description help travelers understand what makes it special.</p><label className="mt-6 block text-sm font-medium">Listing title<input value={values.title} onChange={(event) => update("title", event.target.value)} className={inputClass} placeholder="Oceanfront villa near Montego Bay" /></label><label className="mt-5 block text-sm font-medium">Description<textarea value={values.description} onChange={(event) => update("description", event.target.value)} rows={7} maxLength={3000} className="mt-2 w-full rounded-xl border border-slate-200 p-4 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100" placeholder="Describe the experience, what is included, and what guests should know…" /></label><p className="mt-1 text-right text-xs text-slate-400">{values.description.length}/3000</p></section>}
      {step === 3 && <section><h2 className="text-2xl font-bold">Add location, price, and details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2"><span className="inline-flex items-center gap-2"><MapPin className="size-4" />Location</span><input value={values.location} onChange={(event) => update("location", event.target.value)} className={inputClass} placeholder="Montego Bay, Jamaica" /></label><label className="text-sm font-medium">Price in USD<input value={values.price} onChange={(event) => update("price", event.target.value)} type="number" min="1" step="0.01" className={inputClass} /></label><label className="text-sm font-medium">{values.category === "food" ? "Maximum party size" : values.category === "transport" ? "Seats" : "Guest capacity"}<input value={values.capacity} onChange={(event) => update("capacity", event.target.value)} type="number" min="1" max="100" className={inputClass} /></label>{values.category === "airbnb" && <><label className="text-sm font-medium">Bedrooms<input value={values.bedrooms} onChange={(event) => update("bedrooms", event.target.value)} type="number" min="0" className={inputClass} /></label><label className="text-sm font-medium">Bathrooms<input value={values.bathrooms} onChange={(event) => update("bathrooms", event.target.value)} type="number" min="0" className={inputClass} /></label></>}{values.category === "hotel" && <label className="text-sm font-medium">Star rating<input value={values.star_rating} onChange={(event) => update("star_rating", event.target.value)} type="number" min="1" max="5" className={inputClass} /></label>}{values.category === "transport" && <label className="text-sm font-medium">Luggage capacity<input value={values.luggage} onChange={(event) => update("luggage", event.target.value)} type="number" min="0" className={inputClass} /></label>}<label className="text-sm font-medium sm:col-span-2"><span className="inline-flex items-center gap-2"><ImageIcon className="size-4" />Cover image URL</span><input value={values.image_url} onChange={(event) => update("image_url", event.target.value)} type="url" className={inputClass} placeholder="https://images.unsplash.com/…" /></label><label className="text-sm font-medium sm:col-span-2">Amenities or tags, separated by commas<input value={values.amenities} onChange={(event) => update("amenities", event.target.value)} className={inputClass} placeholder="WiFi, Pool, Breakfast included" /></label></div></section>}
      {step === 4 && <section><h2 className="text-2xl font-bold">Review your draft</h2><p className="mt-2 text-slate-500">Your listing will be saved as a private draft. You can review it before publication.</p><div className="mt-6 overflow-hidden rounded-2xl border border-slate-200"><div className="aspect-[2/1] bg-slate-100 bg-cover bg-center" style={values.image_url ? { backgroundImage: `url(${values.image_url})` } : undefined} /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">{categories.find((item) => item.id === values.category)?.label}</p><h3 className="mt-1 text-2xl font-bold">{values.title}</h3><p className="mt-2 text-sm text-slate-500">{values.location}</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">{values.description}</p><p className="mt-4 text-xl font-bold">${values.price}<span className="text-sm font-medium text-slate-500">{values.category === "food" ? "/person" : values.category === "transport" ? "/day" : "/night"}</span></p></div></div>{Object.entries(values).map(([name, fieldValue]) => <input key={name} type="hidden" name={name} value={fieldValue} />)}{state?.error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{state.error}</p>}</section>}
    </div>
    <footer className="flex items-center justify-between border-t border-slate-100 px-6 py-5 sm:px-8">{step > 1 ? <button type="button" onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-5 py-2.5 text-sm font-semibold"><ArrowLeft className="size-4" />Back</button> : <span />}{step < 4 ? <button type="button" disabled={!canContinue} onClick={() => setStep((current) => current + 1)} className="inline-flex items-center gap-2 rounded-full bg-violet-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Continue<ArrowRight className="size-4" /></button> : <button disabled={pending} className="rounded-full bg-violet-700 px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Creating draft…" : "Create draft listing"}</button>}</footer>
  </form>;
}
