"use client";

import { Bell, BriefcaseBusiness, CreditCard, LockKeyhole, Save, Settings2, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useActionState } from "react";
import { changeSettingsPassword, requestAccountDeletion, saveSettings, signOutEverywhere } from "./actions";

type Values = Record<string, unknown>;
const value = (data: Values, key: string, fallback = "") => typeof data[key] === "string" || typeof data[key] === "number" ? String(data[key]) : fallback;
const enabled = (data: Values, key: string, fallback = false) => typeof data[key] === "boolean" ? Boolean(data[key]) : fallback;
const fieldClass = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100";
const areaClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100";

function Toggle({ name, label, description, defaultChecked }: { name: string; label: string; description?: string; defaultChecked?: boolean }) {
  return <label className="flex items-start justify-between gap-4 border-b border-slate-100 py-3 last:border-0"><span><span className="block text-sm font-medium">{label}</span>{description && <span className="mt-0.5 block text-xs text-slate-500">{description}</span>}</span><input name={name} type="checkbox" defaultChecked={defaultChecked} className="mt-1 size-5 accent-violet-600" /></label>;
}

function Section({ id, icon: Icon, title, description, children }: { id: string; icon: typeof UserRound; title: string; description: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Icon className="size-5" /></span><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div><div className="mt-6">{children}</div></section>;
}

export default function SettingsForm({ profile, settings, host, email, providers, setupWarning }: { profile: Values; settings: Values; host: Values; email: string; providers: string[]; setupWarning: boolean }) {
  const [saveState, saveAction, saving] = useActionState(saveSettings, undefined);
  const [passwordState, passwordAction, changingPassword] = useActionState(changeSettingsPassword, undefined);
  const [deleteState, deleteAction, deleting] = useActionState(requestAccountDeletion, undefined);
  const hostCategories = Array.isArray(host.service_categories) ? host.service_categories.map(String) : [];

  return <div className="grid gap-7 lg:grid-cols-[220px_minmax(0,1fr)]">
    <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3 lg:sticky lg:top-6"><nav className="grid text-sm">{[["account","Account"],["travel","Travel preferences"],["notifications","Notifications"],["billing","Billing"],["booking","Booking defaults"],["host","Host settings"],["security","Privacy & security"]].map(([href,label]) => <a key={href} href={`#${href}`} className="rounded-xl px-3 py-2.5 font-medium text-slate-600 hover:bg-violet-50 hover:text-violet-700">{label}</a>)}</nav></aside>
    <div>
      {setupWarning && <p className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Apply the user settings migration before saving. Defaults are shown until the tables are available.</p>}
      <form action={saveAction} className="space-y-6">
        <Section id="account" icon={UserRound} title="Account" description="Manage your personal information and profile visibility."><div className="grid gap-4 sm:grid-cols-2">
          <label className="text-sm font-medium">Full name<input name="full_name" required defaultValue={value(profile,"full_name")} className={fieldClass} /></label><label className="text-sm font-medium">Email<input value={email} disabled className={`${fieldClass} bg-slate-50 text-slate-500`} /></label>
          <label className="text-sm font-medium">Phone<input name="phone" type="tel" defaultValue={value(profile,"phone")} className={fieldClass} /></label><label className="text-sm font-medium">Date of birth<input name="date_of_birth" type="date" defaultValue={value(profile,"date_of_birth")} className={fieldClass} /></label>
          <label className="text-sm font-medium">Profile photo URL<input name="avatar_url" type="url" defaultValue={value(profile,"avatar_url")} className={fieldClass} /></label><label className="text-sm font-medium">Country / region<input name="country" defaultValue={value(profile,"country")} className={fieldClass} /></label>
          <label className="text-sm font-medium">Language<select name="preferred_language" defaultValue={value(profile,"preferred_language","en")} className={fieldClass}><option value="en">English</option><option value="es">Spanish</option><option value="fr">French</option></select></label><label className="text-sm font-medium">Profile visibility<select name="profile_visibility" defaultValue={value(profile,"profile_visibility","private")} className={fieldClass}><option value="private">Private</option><option value="hosts">Visible to hosts</option><option value="public">Public</option></select></label>
          <label className="text-sm font-medium">Emergency contact<input name="emergency_contact_name" defaultValue={value(profile,"emergency_contact_name")} className={fieldClass} /></label><label className="text-sm font-medium">Emergency phone<input name="emergency_contact_phone" type="tel" defaultValue={value(profile,"emergency_contact_phone")} className={fieldClass} /></label>
        </div></Section>

        <Section id="travel" icon={Settings2} title="Travel preferences" description="Use these defaults to make searching and checkout faster."><div className="grid gap-4 sm:grid-cols-2">
          <label className="text-sm font-medium">Currency<select name="currency" defaultValue={value(settings,"currency","USD")} className={fieldClass}><option>USD</option><option>JMD</option><option>EUR</option><option>GBP</option><option>CAD</option></select></label><label className="text-sm font-medium">Default destination<input name="default_destination" defaultValue={value(settings,"default_destination")} className={fieldClass} /></label>
          <label className="text-sm font-medium">Typical travelers<input name="default_travelers" type="number" min="1" max="30" defaultValue={value(settings,"default_travelers","1")} className={fieldClass} /></label><label className="text-sm font-medium">Vehicle preference<input name="preferred_vehicle_type" defaultValue={value(settings,"preferred_vehicle_type")} className={fieldClass} placeholder="SUV, sedan, accessible van…" /></label>
          <label className="text-sm font-medium">Smoking preference<select name="smoking_preference" defaultValue={value(settings,"smoking_preference","non-smoking")} className={fieldClass}><option value="non-smoking">Non-smoking</option><option value="smoking">Smoking permitted</option><option value="no-preference">No preference</option></select></label><label className="text-sm font-medium sm:col-span-2">Accessibility requirements<textarea name="accessibility_needs" rows={3} defaultValue={value(settings,"accessibility_needs")} className={areaClass} /></label>
          <label className="text-sm font-medium">Accommodation preferences<textarea name="accommodation_preferences" rows={3} defaultValue={value(settings,"accommodation_preferences")} className={areaClass} /></label><label className="text-sm font-medium">Dietary restrictions<textarea name="dietary_restrictions" rows={3} defaultValue={value(settings,"dietary_restrictions")} className={areaClass} /></label>
        </div></Section>

        <Section id="notifications" icon={Bell} title="Notifications" description="Choose the updates you want to receive."><div className="grid gap-x-8 md:grid-cols-2"><div><Toggle name="notify_booking_confirmations" label="Booking confirmations" defaultChecked={enabled(settings,"notify_booking_confirmations",true)} /><Toggle name="notify_booking_reminders" label="Booking reminders" defaultChecked={enabled(settings,"notify_booking_reminders",true)} /><Toggle name="notify_reservation_changes" label="Reservation changes" defaultChecked={enabled(settings,"notify_reservation_changes",true)} /><Toggle name="notify_price_drops" label="Price reductions" defaultChecked={enabled(settings,"notify_price_drops",true)} /><Toggle name="notify_wishlist_availability" label="Wishlist availability" defaultChecked={enabled(settings,"notify_wishlist_availability",true)} /></div><div><Toggle name="notify_promotions" label="Promotional offers" defaultChecked={enabled(settings,"notify_promotions")} /><Toggle name="notify_support_replies" label="Support replies" defaultChecked={enabled(settings,"notify_support_replies",true)} /><Toggle name="notify_email" label="Email notifications" defaultChecked={enabled(settings,"notify_email",true)} /><Toggle name="notify_push" label="Push notifications" defaultChecked={enabled(settings,"notify_push")} /><Toggle name="marketing_consent" label="Marketing consent" defaultChecked={enabled(settings,"marketing_consent")} /></div></div></Section>

        <Section id="billing" icon={CreditCard} title="Payments and billing" description="Billing preferences are stored here; payment credentials stay with a PCI-compliant provider."><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm"><p className="font-semibold">Saved payment methods</p><p className="mt-1 text-slate-500">Stripe is not connected yet. Tourz does not store card numbers.</p><button type="button" disabled className="mt-3 rounded-full bg-slate-200 px-4 py-2 font-semibold text-slate-500">Connect Stripe to add a card</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Receipt email<input name="receipt_email" type="email" defaultValue={value(settings,"receipt_email",email)} className={fieldClass} /></label><label className="text-sm font-medium">Preferred payment<select name="preferred_payment_option" defaultValue="pay_later" className={fieldClass}><option value="pay_later">Pay later</option></select></label><label className="text-sm font-medium">Billing address<textarea name="billing_address" rows={3} defaultValue={value(settings,"billing_address")} className={areaClass} /></label><label className="text-sm font-medium">Invoice details<textarea name="invoice_details" rows={3} defaultValue={value(settings,"invoice_details")} className={areaClass} /></label></div></Section>

        <Section id="booking" icon={ShieldCheck} title="Booking preferences" description="Prefill common details when you reserve."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Default guest count<input name="default_guest_count" type="number" min="1" max="30" defaultValue={value(settings,"default_guest_count","1")} className={fieldClass} /></label><label className="text-sm font-medium">Check-in requirements<textarea name="default_checkin_requirements" rows={3} defaultValue={value(settings,"default_checkin_requirements")} className={areaClass} /></label><label className="text-sm font-medium sm:col-span-2">Default special requests<textarea name="special_requests" rows={3} defaultValue={value(settings,"special_requests")} className={areaClass} /></label></div></Section>

        <Section id="host" icon={BriefcaseBusiness} title="Host settings" description="Configure how you want to offer services on Tourz."><Toggle name="host_enabled" label="Enable host profile" description="Show host tools and onboarding status." defaultChecked={enabled(host,"host_enabled")} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Business / host name<input name="business_name" defaultValue={value(host,"business_name")} className={fieldClass} /></label><label className="text-sm font-medium">Tax country<input name="tax_country" defaultValue={value(host,"tax_country")} className={fieldClass} /></label><fieldset className="sm:col-span-2"><legend className="text-sm font-medium">Service categories</legend><div className="mt-2 flex flex-wrap gap-4">{["airbnb","hotel","food","transport"].map((category) => <label key={category} className="text-sm capitalize"><input type="checkbox" name="service_categories" value={category} defaultChecked={hostCategories.includes(category)} className="mr-2 accent-violet-600" />{category}</label>)}</div></fieldset><label className="text-sm font-medium">Booking approval<select name="booking_approval" defaultValue={value(host,"booking_approval","manual")} className={fieldClass}><option value="manual">Manual approval</option><option value="automatic">Automatic</option></select></label><label className="text-sm font-medium">Cancellation policy<select name="cancellation_policy" defaultValue={value(host,"cancellation_policy","flexible")} className={fieldClass}><option value="flexible">Flexible</option><option value="moderate">Moderate</option><option value="strict">Strict</option></select></label><label className="text-sm font-medium sm:col-span-2">Availability preferences<textarea name="availability_preferences" rows={3} defaultValue={value(host,"availability_preferences")} className={areaClass} /></label></div><Toggle name="auto_confirm" label="Automatically confirm bookings" defaultChecked={enabled(host,"auto_confirm")} /><Toggle name="notify_new_bookings" label="New booking notifications" defaultChecked={enabled(host,"notify_new_bookings",true)} /><Toggle name="notify_cancellations" label="Cancellation notifications" defaultChecked={enabled(host,"notify_cancellations",true)} /><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Payout account: <strong>Not connected</strong> · Tax verification: <strong>Not submitted</strong>. These require an external payout provider.</div></Section>

        {saveState?.error && <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{saveState.error}</p>}{saveState?.success && <p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{saveState.success}</p>}
        <button disabled={saving} className="flex h-12 w-full items-center justify-center gap-2 rounded-full bg-violet-700 font-semibold text-white hover:bg-violet-800 disabled:opacity-60"><Save className="size-4" />{saving ? "Saving…" : "Save all settings"}</button>
      </form>

      <div id="security" className="mt-6 space-y-6 scroll-mt-6">
        <Section id="password" icon={LockKeyhole} title="Privacy and security" description="Manage passwords, sessions, connected accounts, and account removal."><div className="rounded-xl bg-slate-50 p-4 text-sm"><p className="font-semibold">Connected accounts</p><p className="mt-1 capitalize text-slate-500">{providers.length ? providers.join(", ") : "Email and password"}</p></div><form action={passwordAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">New password<input name="password" type="password" minLength={8} required className={fieldClass} /></label><label className="text-sm font-medium">Confirm password<input name="confirmation" type="password" minLength={8} required className={fieldClass} /></label>{passwordState?.error && <p className="text-sm text-rose-700 sm:col-span-2">{passwordState.error}</p>}{passwordState?.success && <p className="text-sm text-emerald-700 sm:col-span-2">{passwordState.success}</p>}<button disabled={changingPassword} className="h-11 rounded-full bg-slate-950 px-5 text-sm font-semibold text-white sm:col-span-2">{changingPassword ? "Updating…" : "Change password"}</button></form><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4 text-sm"><p className="font-semibold">Two-factor authentication</p><p className="mt-1 text-slate-500">Ready for Supabase MFA enrollment; no factor configured.</p></div><form action={signOutEverywhere} className="rounded-xl border border-slate-200 p-4 text-sm"><p className="font-semibold">Active sessions</p><p className="mt-1 text-slate-500">Sign out this account on all devices.</p><button className="mt-3 font-semibold text-violet-700">Sign out everywhere</button></form></div></Section>
        <Section id="delete-account" icon={Trash2} title="Delete account" description="Submit a reviewed deletion request. Your account stays active until processing completes."><form action={deleteAction} className="space-y-4"><label className="block text-sm font-medium">Reason (optional)<textarea name="reason" rows={3} className={areaClass} /></label><label className="block text-sm font-medium">Type DELETE to confirm<input name="confirmation" required className={fieldClass} /></label>{deleteState?.error && <p className="text-sm text-rose-700">{deleteState.error}</p>}{deleteState?.success && <p className="text-sm text-emerald-700">{deleteState.success}</p>}<button disabled={deleting} className="h-11 rounded-full bg-rose-600 px-5 text-sm font-semibold text-white hover:bg-rose-700">{deleting ? "Submitting…" : "Request account deletion"}</button></form></Section>
      </div>
    </div>
  </div>;
}
